name: CI
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'helm/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
      - name: Build
        run: go build -o go-web-app
      - name: Test with the Go CLI
        run: go test ./...
  
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: action-setup-golangci-lint
        uses: golangci/golangci-lint@v3
        with:
          version: v1.0.0
          
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
        - name: Check out the repo
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{github.run_id}}

            
        
